### PR TITLE
close ul-tag in navigation

### PR DESCRIPTION
**Pull request by peterdd**
always close the ul tag to avoid nesting errors, also added \n for readability of resulting html

### CODE REVIEW

**Comment by peterdd** [comment]
changed as requested. please review.

**Comment by vrana** [comment]
There's no need to close `</li>`, it's optional in HTML. Also there's a wrong space in your code. Fixed by d71cb127.

**Comment by peterdd** [comment]
I prefer proper closing, even if HTML5 allows such laziness. It helps debugging for me keeping it xhtml style.

**Comment by vrana** [comment]
One of Adminer's priorities is code size but out of curiosity, how does it help with debugging? What's the difference between `<li>abc</li><li>` and `<li>abc<li>`?

**Pull request closed without merging**
