### PR TITLE
pgsql export constraints

### PR DESCRIPTION
**Pull request by helix84**
Adds features to export in the pgsql driver.

Partially fixes [bug#587](https://sourceforge.net/p/adminer/bugs-and-features/587/).

- export constraints (except TYPEs, to be added)
- first create all tables, only then create all FK constraints (avoids reordering CREATE TABLE statements on order of their FK dependency)

### CODE REVIEW

**Comment by JanTvrdik** [comment]
This would be incredible useful for me as this is by far the biggest issue I encounter when working with Adminer on daily basis.

**Comment by helix84** [comment]
IMO this can be merged. Even if I didn't have time to add support for types, this is an improvement that works as is.

**Comment by vrana** [comment]
Good work. Merged, thanks.

**Comment by JanTvrdik** [comment]
❤️

**Pull request closed without merging**
