### PR TITLE
fix Min_DB::connect (php7 compatibility)

### PR DESCRIPTION
**Pull request by B4nan**
Same purpose as #135, but without other changes

### CODE REVIEW

**Comment by iggyvolz** [comment]
Should this be applied to all of the drivers in adminer/drivers?  I don't have them installed so I can't check.

**Comment by halilim** [comment]
Duplicate of https://github.com/vrana/adminer/pull/153.

**Comment by thaeriac** [comment]
:+1:

**Comment by vrana** [comment]
Fixed, thanks.

**Pull request closed without merging**
