### PR TITLE
<body> class for project-specific styles

### PR DESCRIPTION
**Pull request by lucas-sandery**
Enable editor- or adminer-specific styles by adding an extra class to the body tag.

### CODE REVIEW

**Comment by vrana** [comment]
There's nothing special about Adminer or Adminer Editor, plugins or customizations can alter the UI too.

**Comment by lucas-sandery** [comment]
Closing this without any chance for me to reply was a bit of a knee-jerk reaction.

The markup is reduced in Editor and it'd be far easier, and more readable to others to write CSS selectors that begin with `.editor` or `.adminer` than to write a rule that targets one and "undo"/override it for the other. I have never bothered to make sure my theme works well with Editor simply because you don't provide an easy way to differentiate it.

**Comment by lucas-sandery** [comment]
I've updated the branch. Please consider re-opening this PR.

**Comment by vrana** [comment]
Adminer never used `$GLOBALS` and it doesn't use `global` anymore either.

**Comment by lucas-sandery** [comment]
[The updated branch](https://github.com/vrana/adminer/compare/master...lucas-sandery:adminer:project-class) uses neither. It's not showing here, automatically, because the PR is still closed.

**Comment by vrana** [comment]
I've added the classes. I just hope that I wouldn't regret it in the future because people start depending on a stuff like this in very weird ways.

**Comment by lucas-sandery** [comment]
Cheers.

**Pull request closed without merging**
