### PR TITLE
Fix bug with index generation for new elements in selectAddRow()

### PR DESCRIPTION
**Pull request by djmattyg007**
Instead of incrementing the indice, the code would simply append the
string "1" over and over. It will now behave as expected, the with
indice incrementing by 1 each time.

### CODE REVIEW

**Comment by djmattyg007** [comment]
I've rebased this pull request on top of the latest changes on the master branch.

**Comment by djmattyg007** [comment]
I have again rebased this pull request on top of the latest work on the master branch.

**Comment by vrana** [comment]
What's wrong with appending 1? The goal is to get a higher number which this does.

**Comment by djmattyg007** [comment]
I figured it should be `thing1`, `thing2`, etc. Not `thing1`, `thing11`.

**Pull request closed without merging**
