### PR TITLE
fix PHP7 mysql Min_DB:connect() declaration

### PR DESCRIPTION
**Pull request by MaxiBul**
+ modify .gitignore to allow use index.php in root directory

P.S. sorry if something wrong. This is my first pull request ever.

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
+1 With PHP7, this error occurs on every page:

```
Warning: Declaration of Min_DB::connect($N, $V, $G) should be compatible with 
mysqli::connect($host = NULL, $user = NULL, $password = NULL, $database = NULL, 
$port = NULL, $socket = NULL) in /home/vagrant/Code/adminer/index.php on line 1167
```

**Comment by janbuecker** [comment]
+1

You should only create a PR for the PHP7 issue and do not include the other commits since they don't address the issue itself.

**Comment by MaxiBul** [comment]
@janbuecker These was my first experience with pull requests.
I made only 1 pull request with 1 commit. Other commits was made later for MaxiBul:master. Not for vrana:master. Why they was linked with this pull request? - for me question. Sorry.

**Comment by janbuecker** [comment]
You want to merge your fork's master branch into this master branch. Since you've made changes to your master branch, these changes will be in this PR too. You have to create a new branch, put the commit there and create a PR. I hope I could help you.

**Comment by MaxiBul** [comment]
Thanks! Will try to fix this case :)

**Comment by MaxiBul** [comment]
Looks like fixed. Not this pull request has only 1 commit :)
Thanks again!

**Comment by pavankataria** [comment]
I'm getting this exact same error guys, has this been resolved? 
I pulled the latest commit from the `dev-master` branch.

**Comment by JesseLeite** [comment]
@vrana I'm getting same error w/ PHP7.  @miroc implemented this PR into his adminer wrapper, and all seems fine over there now.  +1 for this fix.

**Comment by halilim** [comment]
Duplicate of https://github.com/vrana/adminer/pull/155.

**Comment by halilim** [comment]
Ping...

**Comment by MaxiBul** [comment]
@halilim Whom ping?

**Comment by halilim** [comment]
@MaxiBul whomever can merge this PR (and do a release) :) I guess @vrana ?

**Comment by vrana** [comment]
Fixed, thanks.

**Comment by ndalliard** [comment]
Sorry guys to reopen this one. But even tough the error disappeared from the frontend of adminer. I get this error message in my errror log from nginx:

    2016/01/26 21:49:03 [error] 3114#0: *17 FastCGI sent in stderr: "PHP
    message: PHP Warning:  Declaration of Min_DB::connect($N, $V, $G) should
    be compatible with mysqli::connect($host = NULL, $user = NULL, $password =
    NULL, $database = NULL, $port = NULL, $socket = NULL) in /usr/share/
    webapps/adminer/index.php on line 1171" while reading response header from
    upstream, client: 154.38.432.8, server: myserver.ch, request: "GET /
    HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "myhost.ch"

I have Adminer 4.2.3 and PHP 7.0.2 installed on ArchLinux with Nginx.

**Comment by vrana** [comment]
This is fixed in Git, not in Adminer 4.2.3.

**Comment by ndalliard** [comment]
Ups. Sorry!

**Pull request closed without merging**
