### PR TITLE
Add a responsive theme based on Nette

### PR DESCRIPTION
**Pull request by AMDG2**
This pull request add a responsive theme and and the viewport meta tag to enable responsiveness with the theme.

### CODE REVIEW

**Comment by vrana** [comment]
I'm not sure that I want width=device-width,initial-scale=1 for Adminer. There's usually lots of data to display.

**Comment by peterpp** [comment]
In my opinion, "width=device-width,initial-scale=1" is currently the best practice not only for responsive websites. This means that confortable clicking and readable font size have bigger priority than displaying whole page. If you want to see more data at once, you can still zoom the page.

**Comment by AMDG2** [comment]
I agree with @peterpp I use a lot adminer from my mobile device. Because of that I really need a responsive interface. 
@vrana If you don't wan't to integrate this patch perhaps we can add a hook for extensions to add HTML tags in the header ?

**Comment by peterpp** [comment]
@AMDG2, you can tweak meta headers in plugin. Take a look at our responsive theme: https://github.com/pematon/adminer-theme

**Comment by AMDG2** [comment]
@peterpp Great theme, I did not knew about that one. 
@vrana Is it possible to add a link on adminer page to this theme ? So people who want to use adminer from mobile could easily know about this responsive theme !

**Comment by vrana** [comment]
Implement this as a plugin. Linked https://github.com/pematon/adminer-theme from https://www.adminer.org/plugins/.

**Pull request closed without merging**
