### PR TITLE
Fixed compatiblity with PHP 7

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by stychos** [comment]
Oh hell, just maked same corrections locally :)

**Comment by rap2hpoutre** [comment]
+1 for this :)

**Comment by pelletiermaxime** [comment]
Not sure if anyone is actually reading PRs here, but adding my +1 !

**Comment by dg** [comment]
ping @vrana 

It is impossible to be compatible with both PHP 4 and PHP 7, so I think it's time to leave PHP 4.

**Comment by ejzy** [comment]
+1 for this
+1 for leaving PHP 4

**Comment by vrana** [comment]
Merged, thanks.

**Comment by rap2hpoutre** [comment]
@vrana Any release planned for this fix?

**Pull request closed without merging**
