### PR TITLE
set of UX plugins for phpMyAdmin users + few fixes/optimizations

### PR DESCRIPTION
**Pull request by SailorMax**
Fix edit multiple checked records
Recognize emails with name (sample: name &lt;email@foo.com&gt;)
Fix paginator page 1 (first) skin
Fix table pages top links (all pages, which related to selected table, has similar links)
Optimize referencable_primary() for MySQL
Remove duplicates of collation-lists on `Alter table` page. Require JavaScript on client side! But support "nojs=1" argument to return old method
Add style chooser to select data export
Support export table rows without AI keys
Output binary UUID in hex
Fix disabled &lt;select&gt; UI in Chrome
Add detect `SQL command` page when URL containt '&table=' (allow to use UX plugin sql_command_table_fields)
Support receive partial data for alter table (workaround for max_input_vars limit errors) (allow to use UX plugin table_edit_by_fields)
UX plugins for simpler migrate phpMyAdmin users:
- `tables_list_name_select`:   table names in menu has link to `Select data`, and icons to `Show structure`
- `tables_list_filter`:    table list in menu has filter field
- `duplicate_result_controls`:  duplicate paginator before result table
- `frameset_simulator`:    simulate frames in UI
- `disable_highlight`:    disable code highlight
- `executed_query_output_modifier`: &ltcode&gt; text wrap + possibility to show full query + possibility to always show executed query
- `submit_at_right`:     move `submit` buttons to the right
- `table_hscroll_followers`:   do not scroll some page elements (pages list, SQL code,...) while horizontal scroll the page
- `sql_command_table_fields`:  add table fields chooser on `SQL command` page
- `export_per_table`:    copy "Export" link to table links list
- `table_structure_advanced`:  display table status, table manipulations (+ table rename), export data and edit table controls on table structure page
- `table_edit_by_fields`:   disable by default input fields on `Alter table` page, to reduce count of submitted values
- `table_record_field_details`:  display field comments on record edit page
- `table_sort_desc_before_title`: output `desc` link before columnt title
- `db_diagnostics_queries`:   display shortcut to diagnostic queries for database/driver. Currently only for MySQL.
- `sql_command_transaction`:        detect "START TRANSACTION" to setup "Stop on error" checkbox

### CODE REVIEW

**Comment by djmattyg007** [comment]
A pull request this large is very difficult to review. You should probably consider splitting it up.

**Comment by SailorMax** [comment]
@djmattyg007 Sorry. This pull request grow up since November 2015 in one direction - set of UX plugins (plugins/ux/). Other fixes was made together, because at start of this year I was novice in Git + made for just for my self. Adminer author do not show any signs of interest here. In current situation I don't see the reason spend time on any splits.
You have access to each commit with changes. If you need some additional information - I ready to answer.

**Comment by klonos** [comment]
> because at start of this year I was novice in Git + made it just for my self.

...I'm sure one year later you know GitHub enough to make a fork of the project and then merge your changes in your own fork. This way,you allow people that find your fixes useful to download a ready version of adminer with your improvements and fixes implemented 😉

**Comment by djmattyg007** [comment]
I have already done this :)

**Comment by SailorMax** [comment]
@klonos This pull request = my fork. You can see it here: https://github.com/SailorMax/myAdminer
By this pull request I offer to Adminer author got my changes :)

**Comment by vrana** [comment]
This is too big too merge. Please create individual pull requests for individual changes. I couldn't find most of the improvements mentioned in the description of this pull requests in the commits of this pull request.

**Comment by SailorMax** [comment]
@vrana 
Too late for individual changes. Too many combined changes.
But if in the future there will be interest in my edits, I added to description name of commits to easier find changes in your files. All other commits - my UX plugins + some fixes.

Sorry for so tangled pull request.

**Pull request closed without merging**
