### PR TITLE
PostgreSQL data SQL export hotfix

### PR DESCRIPTION
**Pull request by maresja1**
Hey, 

I know this is really just a hotfix, but thanks to adding this function I am able to export data to SQL with PostgreSQL. Others might be interested in having that option. Before it gave just a blank page (no error, nothing).

Btw. if there is a better way of handling missing functionalities in drivers, I will gladly adopt it in this PR.

Thx for a brilliant tool.

### CODE REVIEW

**Comment by ejzy** [comment]
There are already #137 and #152 pull requests that solve real structure exporting, but sadly not merged for months.

**Comment by maresja1** [comment]
Oh, I see, sorry for duplicating. Feel free to close the PR. May I ask, why aren't they merged?

**Comment by kusmierz** [comment]
ask @vrana ;)

**Comment by vrana** [comment]
Feature support is declared by `Min_DB::support`.

**Pull request closed without merging**
