### PR TITLE
- #1 adds the plugin to enable customizing the theme based on the ser…

### PR DESCRIPTION
**Pull request by mmokross**
As I was in the need to customize the theme used in the **_adminer_** based on the selected SQL server, I implemented a small plugin for this.

Maybe it's of interest for some users. Please feel free to grap it and adapt anything, that is not in line.

### CODE REVIEW

**Comment by vrana** [comment]
Please put this somewhere (e.g. your repo or Gist) and I can then link it from https://www.adminer.org/plugins/#user.

**Comment by mmokross** [comment]
Is this the information you need?

The plugin AdminerCustomizeThemeBasedOnServer in https://github.com/mmokross/adminer
enables the customization of the active theme based on the active server selected.

It tries to add a SERVER specific CSS file using the following convention
- same directory as adminer.css
- name it server-[SERVER]-adminer.css
- add any additional CSS styles, you want to apply to the adminer.css
  or the default.css

See the example in https://github.com/mmokross/adminer
- adminer/plugin.php to add the plugin AdminerCustomizeThemeBasedOnServer
- adminer/server-MY.LOCAL-adminer.css
- adminer/server-MY.LOCAL-ICON.png
- plugins/customize-theme-by-server.php
- run the adminer/index.php and set server to MY.LOCAL

**Comment by vrana** [comment]
I mean put somewhere just the plugin, not the whole forked Adminer.

**Comment by mmokross** [comment]
Ok, I'll do it the next days.

**Comment by mmokross** [comment]
Is the following solution practicable? https://github.com/mmokross/AdminerCustomizeThemeBasedOnServer

**Comment by vrana** [comment]
Thanks, linked.

**Pull request closed without merging**
