### PR TITLE
Fix PHP7 Compatibility

### PR DESCRIPTION
**Pull request by iggyvolz**
See http://sourceforge.net/p/adminer/bugs-and-features/477/ for a description of the bug.

Using $_, $__, and $___ for unused parameters (which must be unique) - this can be anything as long as it is unused.

### CODE REVIEW

**Comment by thaeriac** [comment]
:+1:

**Comment by integer** [comment]
Same issue on my machine with PHP 7.0.1 and Adminer 4.2.3. 

@iggyvolz , thanks for your pull. Here is my small review: would be nice if you could change formatting (spaces) for default values as it is in rest of project. Unused parameters naming would be IMHO better as it is in `mysqli::connect` - `$database = null, $port = null, $socket = null`. Variables with underscores are little confusing.

**Comment by integer** [comment]
@iggyvolz , did you see https://github.com/vrana/adminer/pull/155 - fixing same issue and keeps support for `$server` in format `<host>:<port>`. It's backward compatible.

**Comment by iggyvolz** [comment]
Understood.  I thought that didn't fix this issue which is why I kept it open, but it looks like it does.

**Pull request closed without merging**
