### PR TITLE
Fix broken html

### PR DESCRIPTION
**Pull request by morpheus-87**
This PR fixes the broken html, that the php script produces.

### CODE REVIEW

**Comment by vrana** [comment]
The HTML is not broken, all these tags are optional.

**Comment by morpheus-87** [comment]
But what is the problem to add the closing tags?

**Comment by vrana** [comment]
There's no point in doing so. It only increases code size with no benefit. Make your content-adding script smarter by adding the content at the end of the page if there's no `</body>`.

**Comment by morpheus-87** [comment]
It makes the code much more human-readable and the increase of code size is nearly nothing.

**Pull request closed without merging**
