### PR TITLE
added mongodb PHP7 beta driver.

### PR DESCRIPTION
**Pull request by pivolan**
Work only insert, update, list database, list index, list tables. select, where, limit, order, delete, edit, edit from select.
does not work structure modify, index, modify, custom queries, export, import, groups, collections drop, add.

### CODE REVIEW

**Comment by vrana** [comment]
1. Please make sure that this compiles in PHP 5.3 (no short array syntax, maybe others).
1. Do not put `{` on the beginning of the line. Put it on the end of the previous line.

**Comment by vrana** [comment]
There's already `mongo.inc.php`. Can you merge these two?

**Comment by pivolan** [comment]
1. Fixed
2. fixed
In mongo.inc.php another version of driver, and there is nothing to merge. Versions between two drivers incompatible.

**Comment by vrana** [comment]
See the other drivers. They are like:

    if (extension_loaded("mysqli")) {
      // mysqli specific code
    } elseif (extension_loaded("mysql") {
      // mysql specific code
    }

Do the same.

**Comment by pivolan** [comment]
too many diffs, can't do this, sorry.

**Comment by fidraj** [comment]
So this was never implemented?

**Comment by pivolan** [comment]
I think yes. In old mongo drivers less functions than in new. And I don't know functionality in old mongodb drivers. So it's too difficult for me, to merge two versions.
Also I think that we shouldn't merge two drivers, because new client incompatible with old server, and old client incompatible with new client. So for different servers we should use difference drivers.
Sorry for my English.

**Pull request closed without merging**
