### PR TITLE
Adminer theme

### PR DESCRIPTION
**Pull request by alekseymvt**
Mvt Adminer theme.
adminer

### CODE REVIEW

**Comment by alekseymvt** [comment]
Now I will check 4.6.3...

**Comment by alekseymvt** [comment]
Now I understand. I did not test the Editor.
Now I'll look.

**Comment by alekseymvt** [comment]
It's easy not to fix it. We need to add an additional selector to the parent node. I'll try to find now how to add....

**Comment by alekseymvt** [comment]
If Vrana takes commit https://github.com/vrana/adminer/pull/298 , then I can add styles for Editor

**Comment by BarbzYHOOL** [comment]
@vrana looks rad

**Comment by vrana** [comment]
Merged.

**Comment by vrana** [comment]
Download it from https://raw.githubusercontent.com/vrana/adminer/master/designs/mvt/adminer.css and put in the same directory as Adminer.

**Comment by alekseymvt** [comment]
Write here if you find bugs.

**Comment by alekseymvt** [comment]
@apmuthu https://github.com/vrana/adminer/pull/302/files

**Pull request closed without merging**
